# Generated by Django 4.0 on 2023-07-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='review_text',
        ),
    ]
